
## 主题名称：Catppuccin Mocha 🌿
## 作者：Pocco81 (https://github.com/Pocco81)
## 协议：MIT
## 上游： https://github.com/catppuccin/kitty/blob/main/mocha.conf
## 简介：偏柔和的粉彩终端主题。



# 基础前景和背景颜色。
foreground              #CDD6F4
background              #1E1E2E
selection_foreground    #1E1E2E
selection_background    #F5E0DC

# 光标颜色。
cursor                  #F5E0DC
cursor_text_color       #1E1E2E

# 鼠标悬停 URL 时的下划线颜色。
url_color               #B4BEFE

# Kitty 窗口边框颜色。
active_border_color     #CBA6F7
inactive_border_color   #8E95B3
bell_border_color       #EBA0AC

# 系统窗口标题栏颜色。
wayland_titlebar_color system
macos_titlebar_color system

# 标签栏颜色。
active_tab_foreground   #11111B
active_tab_background   #CBA6F7
inactive_tab_foreground #CDD6F4
inactive_tab_background #181825
tab_bar_background      #11111B

# 终端内标记文本的颜色。
mark1_foreground #1E1E2E
mark1_background #87B0F9
mark2_foreground #1E1E2E
mark2_background #CBA6F7
mark3_foreground #1E1E2E
mark3_background #74C7EC

# 16 色终端调色板。

# 黑色。
color0 #43465A
color8 #43465A

# 红色。
color1 #F38BA8
color9 #F38BA8

# 绿色。
color2  #A6E3A1
color10 #A6E3A1

# 黄色。
color3  #F9E2AF
color11 #F9E2AF

# 蓝色。
color4  #87B0F9
color12 #87B0F9

# 品红色。
color5  #F5C2E7
color13 #F5C2E7

# 青色。
color6  #94E2D5
color14 #94E2D5

# 白色。
color7  #CDD6F4
color15 #A1A8C9
