# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[manager]

keymap = [
  { on = "u", run = "plugin unzip", desc = "解压缩选定的文件" },
  { on = "T", run = "plugin max-preview", desc = "将预览最大化" },
  { on = [ "c", "a" ], run = "plugin compress", desc = "将选定文件压缩为压缩包" },
  { on = "l", run = "plugin smart-enter", desc = "按l直接打开文件" },
  { on = "<Esc>", run = "escape", desc = "退出可视模式，清除选择，或取消搜索" },
  { on = "<C-[>", run = "escape", desc = "退出可视模式，清除选择，或取消搜索" },
  { on = "q", run = "quit", desc = "退出进程" },
  { on = "Q", run = "quit --no-cwd-file", desc = "退出进程，不输出 cwd 文件" },
  { on = "<C-c>", run = "close", desc = "关闭当前标签页，若为最后一个则退出" },
  { on = "<C-z>", run = "suspend", desc = "挂起进程" },

  # Hopping
  { on = "k", run = "arrow -1", desc = "将光标上移" },
  { on = "j", run = "arrow 1", desc = "将光标下移" },

  { on = "<Up>", run = "arrow -1", desc = "将光标上移" },
  { on = "<Down>", run = "arrow 1", desc = "将光标下移" },

  { on = "<C-u>", run = "arrow -50%", desc = "将光标上移半页" },
  { on = "<C-d>", run = "arrow 50%", desc = "将光标下移半页" },
  { on = "<C-b>", run = "arrow -100%", desc = "将光标上移一页" },
  { on = "<C-f>", run = "arrow 100%", desc = "将光标下移一页" },

  { on = "<S-PageUp>", run = "arrow -50%", desc = "将光标上移半页" },
  { on = "<S-PageDown>", run = "arrow 50%", desc = "将光标下移半页" },
  { on = "<PageUp>", run = "arrow -100%", desc = "将光标上移一页" },
  { on = "<PageDown>", run = "arrow 100%", desc = "将光标下移一页" },

  { on = [ "g", "g" ], run = "arrow -99999999", desc = "将光标移动到顶部" },
  { on = "G", run = "arrow 99999999", desc = "将光标移动到底部" },

  # Navigation
  { on = "h", run = "leave", desc = "返回父目录" },
  { on = "l", run = "enter", desc = "进入子目录" },

  { on = "<Left>", run = "leave", desc = "返回父目录" },
  { on = "<Right>", run = "enter", desc = "进入子目录" },

  { on = "H", run = "back", desc = "返回上一个目录" },
  { on = "L", run = "forward", desc = "前往下一个目录" },

  # Toggle
  { on = "<Space>", run = [ "toggle", "arrow 1" ], desc = "切换当前选择状态" },
  { on = "<C-a>", run = "toggle_all --state=on", desc = "选择所有文件" },
  { on = "<C-r>", run = "toggle_all", desc = "反选所有文件" },

  # Visual mode
  { on = "v", run = "visual_mode", desc = "进入可视模式（选择模式）" },
  { on = "V", run = "visual_mode --unset", desc = "进入可视模式（取消模式）" },

  # Seeking
  { on = "K", run = "seek -5", desc = "在预览中上移5个单位" },
  { on = "J", run = "seek 5", desc = "在预览中下移5个单位" },

  # Spotting
  { on = "<Tab>", run = "spot", desc = "标记悬停的文件" },

  # Operation
  { on = "o", run = "open --interactive", desc = "交互式打开选定的文件" },
  { on = "O", run = "open --interactive", desc = "交互式打开选定的文件" },
  { on = "<Enter>", run = "open", desc = "打开选定的文件" },
  { on = "<S-Enter>", run = "open --interactive", desc = "交互式打开选定的文件" },
  { on = "y", run = "yank", desc = "复制选定的文件（复制）" },
  { on = "x", run = "yank --cut", desc = "剪切选定的文件" },
  { on = "p", run = "paste", desc = "粘贴复制的文件" },
  { on = "P", run = "paste --force", desc = "粘贴复制的文件（如目标存在则覆盖）" },
  { on = "-", run = "link", desc = "为复制的文件创建符号链接（绝对路径）" },
  { on = "_", run = "link --relative", desc = "为复制的文件创建符号链接（相对路径）" },
  { on = "<C-->", run = "hardlink", desc = "为复制的文件创建硬链接" },
  { on = "Y", run = "unyank", desc = "取消复制状态" },
  { on = "X", run = "unyank", desc = "取消复制状态" },
  { on = "d", run = "remove", desc = "移动选定的文件到垃圾箱" },
  { on = "D", run = "remove --permanently", desc = "永久删除选定的文件" },
  { on = "a", run = "create", desc = "创建一个文件（以 / 结尾表示目录）" },
  { on = "r", run = "rename --cursor=before_ext", desc = "重命名选定的文件" },
  { on = ";", run = "shell --interactive", desc = "运行一个 shell 命令" },
  { on = ":", run = "shell --block --interactive", desc = "运行一个 shell 命令（阻塞直到完成）" },
  { on = ".", run = "hidden toggle", desc = "切换隐藏文件的可见性" },
  { on = "s", run = "search --via=fd", desc = "通过 fd 按名称搜索文件" },
  { on = "S", run = "search --via=rg", desc = "通过 ripgrep 按内容搜索文件" },
  { on = "<C-s>", run = "escape --search", desc = "取消正在进行的搜索" },
  { on = "z", run = "plugin zoxide", desc = "通过 zoxide 跳转到目录" },
  { on = "Z", run = "plugin fzf", desc = "通过 fzf 跳转到文件/目录" },

  # Linemode
  { on = [ "m", "s" ], run = "linemode size", desc = "行模式：按大小" },
  { on = [ "m", "p" ], run = "linemode permissions", desc = "行模式：按权限" },
  { on = [ "m", "b" ], run = "linemode btime", desc = "行模式：按创建时间" },
  { on = [ "m", "m" ], run = "linemode mtime", desc = "行模式：按修改时间" },
  { on = [ "m", "o" ], run = "linemode owner", desc = "行模式：按所有者" },
  { on = [ "m", "n" ], run = "linemode none", desc = "行模式：无" },

  # Copy
  { on = [ "c", "c" ], run = "copy path", desc = "复制文件路径" },
  { on = [ "c", "d" ], run = "copy dirname", desc = "复制目录路径" },
  { on = [ "c", "f" ], run = "copy filename", desc = "复制文件名" },
  { on = [ "c", "n" ], run = "copy name_without_ext", desc = "复制不带扩展名的文件名" },

  # Filter
  { on = "f", run = "filter --smart", desc = "过滤文件" },

  # Find
  { on = "/", run = "find --smart", desc = "查找下一个文件" },
  { on = "?", run = "find --previous --smart", desc = "查找上一个文件" },
  { on = "n", run = "find_arrow", desc = "跳转到下一个找到的" },
  { on = "N", run = "find_arrow --previous", desc = "跳转到上一个找到的" },

  # Sorting
  { on = [ ",", "m" ], run = [ "sort mtime --reverse=no", "linemode mtime" ], desc = "按修改时间排序" },
  { on = [ ",", "M" ], run = [ "sort mtime --reverse", "linemode mtime" ], desc = "按修改时间逆序排序" },
  { on = [ ",", "b" ], run = [ "sort btime --reverse=no", "linemode btime" ], desc = "按创建时间排序" },
  { on = [ ",", "B" ], run = [ "sort btime --reverse", "linemode btime" ], desc = "按创建时间逆序排序" },
  { on = [ ",", "e" ], run = "sort extension --reverse=no", desc = "按扩展名排序" },
  { on = [ ",", "E" ], run = "sort extension --reverse", desc = "按扩展名逆序排序" },
  { on = [ ",", "a" ], run = "sort alphabetical --reverse=no", desc = "按字母顺序排序" },
  { on = [ ",", "A" ], run = "sort alphabetical --reverse", desc = "按字母逆序排序" },
  { on = [ ",", "n" ], run = "sort natural --reverse=no", desc = "按自然顺序排序" },
  { on = [ ",", "N" ], run = "sort natural --reverse", desc = "按自然逆序排序" },
  { on = [ ",", "s" ], run = [ "sort size --reverse=no", "linemode size" ], desc = "按大小排序" },
  { on = [ ",", "S" ], run = [ "sort size --reverse", "linemode size" ], desc = "按大小逆序排序" },
  { on = [ ",", "r" ], run = "sort random --reverse=no", desc = "随机排序" },

  # Goto
  { on = [ "g", "h" ], run = "cd ~", desc = "前往主目录" },
  { on = [ "g", "c" ], run = "cd ~/.config", desc = "前往配置目录" },
  { on = [ "g", "d" ], run = "cd ~/Downloads", desc = "前往下载目录" },
  { on = [ "g", "<Space>" ], run = "cd --interactive", desc = "交互式跳转" },

  # Tabs
  { on = "t", run = "tab_create --current", desc = "使用当前工作目录创建一个新标签页" },

  { on = "1", run = "tab_switch 0", desc = "切换到第一个标签页" },
  { on = "2", run = "tab_switch 1", desc = "切换到第二个标签页" },
  { on = "3", run = "tab_switch 2", desc = "切换到第三个标签页" },
  { on = "4", run = "tab_switch 3", desc = "切换到第四个标签页" },
  { on = "5", run = "tab_switch 4", desc = "切换到第五个标签页" },
  { on = "6", run = "tab_switch 5", desc = "切换到第六个标签页" },
  { on = "7", run = "tab_switch 6", desc = "切换到第七个标签页" },
  { on = "8", run = "tab_switch 7", desc = "切换到第八个标签页" },
  { on = "9", run = "tab_switch 8", desc = "切换到第九个标签页" },

  { on = "[", run = "tab_switch -1 --relative", desc = "切换到上一个标签页" },
  { on = "]", run = "tab_switch 1 --relative", desc = "切换到下一个标签页" },

  { on = "{", run = "tab_swap -1", desc = "与上一个标签页交换当前标签页" },
  { on = "}", run = "tab_swap 1", desc = "与下一个标签页交换当前标签页" },

  # Tasks
  { on = "w", run = "tasks_show", desc = "显示任务管理器" },

  # Help
  { on = "~", run = "help", desc = "打开帮助" },
  { on = "<F1>", run = "help", desc = "打开帮助" },
]

[tasks]

keymap = [
  { on = "<Esc>", run = "close", desc = "关闭任务管理器" },
  { on = "<C-[>", run = "close", desc = "关闭任务管理器" },
  { on = "<C-c>", run = "close", desc = "关闭任务管理器" },
  { on = "w", run = "close", desc = "关闭任务管理器" },

  { on = "k", run = "arrow -1", desc = "将光标上移" },
  { on = "j", run = "arrow 1", desc = "将光标下移" },

  { on = "<Up>", run = "arrow -1", desc = "将光标上移" },
  { on = "<Down>", run = "arrow 1", desc = "将光标下移" },

  { on = "<Enter>", run = "inspect", desc = "检查任务" },
  { on = "x", run = "cancel", desc = "取消任务" },

  # Help
  { on = "~", run = "help", desc = "打开帮助" },
  { on = "<F1>", run = "help", desc = "打开帮助" },
]

[spot]

keymap = [
  { on = "<Esc>", run = "close", desc = "关闭 spot" },
  { on = "<C-[>", run = "close", desc = "关闭 spot" },
  { on = "<C-c>", run = "close", desc = "关闭 spot" },
  { on = "<Tab>", run = "close", desc = "关闭 spot" },

  { on = "k", run = "arrow -1", desc = "将光标上移" },
  { on = "j", run = "arrow 1", desc = "将光标下移" },
  { on = "h", run = "swipe -1", desc = "向下一个文件滑动" },
  { on = "l", run = "swipe 1", desc = "向上一个文件滑动" },

  { on = "<Up>", run = "arrow -1", desc = "将光标上移" },
  { on = "<Down>", run = "arrow 1", desc = "将光标下移" },
  { on = "<Left>", run = "swipe -1", desc = "向下一个文件滑动" },
  { on = "<Right>", run = "swipe 1", desc = "向上一个文件滑动" },

  # Copy
  { on = [ "c", "c" ], run = "copy cell", desc = "复制选定的单元格" },

  # Help
  { on = "~", run = "help", desc = "打开帮助" },
  { on = "<F1>", run = "help", desc = "打开帮助" },
]

[pick]

keymap = [
  { on = "<Esc>", run = "close", desc = "取消选择" },
  { on = "<C-[>", run = "close", desc = "取消选择" },
  { on = "<C-c>", run = "close", desc = "取消选择" },
  { on = "<Enter>", run = "close --submit", desc = "提交选择" },

  { on = "k", run = "arrow -1", desc = "将光标上移" },
  { on = "j", run = "arrow 1", desc = "将光标下移" },

  { on = "<Up>", run = "arrow -1", desc = "将光标上移" },
  { on = "<Down>", run = "arrow 1", desc = "将光标下移" },

  # Help
  { on = "~", run = "help", desc = "打开帮助" },
  { on = "<F1>", run = "help", desc = "打开帮助" },
]

[input]

keymap = [
  { on = "<C-c>", run = "close", desc = "取消输入" },
  { on = "<Enter>", run = "close --submit", desc = "提交输入" },
  { on = "<Esc>", run = "escape", desc = "返回普通模式，或取消输入" },
  { on = "<C-[>", run = "escape", desc = "返回普通模式，或取消输入" },

  # Mode
  { on = "i", run = "insert", desc = "进入插入模式" },
  { on = "a", run = "insert --append", desc = "进入追加模式" },
  { on = "I", run = [ "move -999", "insert" ], desc = "移动到行首，并进入插入模式" },
  { on = "A", run = [ "move 999", "insert --append" ], desc = "移动到行尾，并进入追加模式" },
  { on = "v", run = "visual", desc = "进入可视模式" },
  { on = "V", run = [ "move -999", "visual", "move 999" ], desc = "进入可视模式并选择所有内容" },

  # Character-wise movement
  { on = "h", run = "move -1", desc = "后移一个字符" },
  { on = "l", run = "move 1", desc = "前移一个字符" },
  { on = "<Left>", run = "move -1", desc = "后移一个字符" },
  { on = "<Right>", run = "move 1", desc = "前移一个字符" },
  { on = "<C-b>", run = "move -1", desc = "后移一个字符" },
  { on = "<C-f>", run = "move 1", desc = "前移一个字符" },

  # Word-wise movement
  { on = "b", run = "backward", desc = "移动到当前或上一个单词的开头" },
  { on = "w", run = "forward", desc = "移动到下一个单词的开头" },
  { on = "e", run = "forward --end-of-word", desc = "移动到当前或下一个单词的末尾" },
  { on = "<A-b>", run = "backward", desc = "移动到当前或上一个单词的开头" },
  { on = "<A-f>", run = "forward --end-of-word", desc = "移动到当前或下一个单词的末尾" },

  # Line-wise movement
  { on = "0", run = "move -999", desc = "移动到行首" },
  { on = "$", run = "move 999", desc = "移动到行尾" },
  { on = "<C-a>", run = "move -999", desc = "移动到行首" },
  { on = "<C-e>", run = "move 999", desc = "移动到行尾" },
  { on = "<Home>", run = "move -999", desc = "移动到行首" },
  { on = "<End>", run = "move 999", desc = "移动到行尾" },

  # Delete
  { on = "<Backspace>", run = "backspace", desc = "删除光标前的字符" },
  { on = "<Delete>", run = "backspace --under", desc = "删除光标下的字符" },
  { on = "<C-h>", run = "backspace", desc = "删除光标前的字符" },
  { on = "<C-d>", run = "backspace --under", desc = "删除光标下的字符" },

  # Kill
  { on = "<C-u>", run = "kill bol", desc = "杀死到行首" },
  { on = "<C-k>", run = "kill eol", desc = "杀死到行尾" },
  { on = "<C-w>", run = "kill backward", desc = "杀死到当前单词的开头" },
  { on = "<A-d>", run = "kill forward", desc = "杀死到当前单词的末尾" },

  # Cut/Yank/Paste
  { on = "d", run = "delete --cut", desc = "剪切选定的字符" },
  { on = "D", run = [ "delete --cut", "move 999" ], desc = "剪切到行尾" },
  { on = "c", run = "delete --cut --insert", desc = "剪切选定的字符，并进入插入模式" },
  { on = "C", run = [ "delete --cut --insert", "move 999" ], desc = "剪切到行尾，并进入插入模式" },
  { on = "x", run = [ "delete --cut", "move 1 --in-operating" ], desc = "剪切当前字符" },
  { on = "y", run = "yank", desc = "复制选定的字符" },
  { on = "p", run = "paste", desc = "在光标后粘贴复制的字符" },
  { on = "P", run = "paste --before", desc = "在光标前粘贴复制的字符" },

  # Undo/Redo
  { on = "u", run = "undo", desc = "撤销上一个操作" },
  { on = "<C-r>", run = "redo", desc = "重做上一个操作" },

  # Help
  { on = "~", run = "help", desc = "打开帮助" },
  { on = "<F1>", run = "help", desc = "打开帮助" },
]

[confirm]

keymap = [
  { on = "<Esc>", run = "close", desc = "取消确认" },
  { on = "<C-[>", run = "close", desc = "取消确认" },
  { on = "<C-c>", run = "close", desc = "取消确认" },
  { on = "<Enter>", run = "close --submit", desc = "提交确认" },

  { on = "n", run = "close", desc = "取消确认" },
  { on = "y", run = "close --submit", desc = "提交确认" },

  { on = "k", run = "arrow -1", desc = "将光标上移" },
  { on = "j", run = "arrow 1", desc = "将光标下移" },

  { on = "<Up>", run = "arrow -1", desc = "将光标上移" },
  { on = "<Down>", run = "arrow 1", desc = "将光标下移" },

  # Help
  { on = "~", run = "help", desc = "打开帮助" },
  { on = "<F1>", run = "help", desc = "打开帮助" },
]

[completion]

keymap = [
  { on = "<C-c>", run = "close", desc = "取消完成" },
  { on = "<Tab>", run = "close --submit", desc = "提交完成" },
  { on = "<Enter>", run = [ "close --submit", "close_input --submit" ], desc = "提交完成并提交输入" },

  { on = "<A-k>", run = "arrow -1", desc = "将光标上移" },
  { on = "<A-j>", run = "arrow 1", desc = "将光标下移" },

  { on = "<Up>", run = "arrow -1", desc = "将光标上移" },
  { on = "<Down>", run = "arrow 1", desc = "将光标下移" },

  { on = "<C-p>", run = "arrow -1", desc = "将光标上移" },
  { on = "<C-n>", run = "arrow 1", desc = "将光标下移" },

  # Help
  { on = "~", run = "help", desc = "打开帮助" },
  { on = "<F1>", run = "help", desc = "打开帮助" },
]

[help]

keymap = [
  { on = "<Esc>", run = "escape", desc = "清除过滤器，或隐藏帮助" },
  { on = "<C-[>", run = "escape", desc = "清除过滤器，或隐藏帮助" },
  { on = "<C-c>", run = "close", desc = "隐藏帮助" },

  # Navigation
  { on = "k", run = "arrow -1", desc = "将光标上移" },
  { on = "j", run = "arrow 1", desc = "将光标下移" },

  { on = "<Up>", run = "arrow -1", desc = "将光标上移" },
  { on = "<Down>", run = "arrow 1", desc = "将光标下移" },

  # Filtering
  { on = "f", run = "filter", desc = "为帮助项应用过滤器" },
]
